FROM python:3.13.7-slim-trixie

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential && apt-get install -y --no-install-recommends curl ca-certificates && rm -rf /var/lib/apt/lists/*

COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENTRYPOINT ["/entrypoint.sh"]

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]