# Generated by Django 6.0.2 on 2026-02-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_task_description_alter_task_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
