# Generated by Django 6.0.2 on 2026-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
